"""Auto-generated from INVARIANT_CATALOG.md by tools/catalog.py.

DO NOT EDIT BY HAND. Regenerate via:

    python -m tools.catalog generate-ids

This file is the source of truth for I-CAT-01 (every REQUIRED or
STRUCTURAL catalog row has a corresponding @register entry).
"""
from __future__ import annotations

EXPECTED_REQUIRED_IDS: frozenset[str] = frozenset({
    "I-AFF-01",
    "I-AFF-02",
    "I-AFF-03",
    "I-AFF-04",
    "I-AFF-05",
    "I-AFF-06",
    "I-AFF-11",
    "I-AFF-12",
    "I-AFF-13",
    "I-AGN-01",
    "I-AGN-02",
    "I-AGN-03",
    "I-AGN-04",
    "I-AGN-05",
    "I-AGN-06",
    "I-APRJ-01",
    "I-APRJ-02",
    "I-APRJ-03",
    "I-APRJ-04",
    "I-APRJ-05",
    "I-APRJ-06",
    "I-BHV-01",
    "I-IBND-01",
    "I-IBND-02",
    "I-IBND-03",
    "I-IBND-04",
    "I-INT-01",
    "I-INT-02",
    "I-LLM-01",
    "I-LLM-03",
    "I-MOD-01",
    "I-MOD-02",
    "I-MOD-03",
    "I-MOD-04",
    "I-MOD-05",
    "I-MSI-01",
    "I-MSI-02",
    "I-MSI-03",
    "I-MSI-04",
    "I-MSI-05",
    "I-MSI-06",
    "I-PCE-01",
    "I-PCE-02",
    "I-PCE-03",
    "I-PCE-04",
    "I-PMAP-02",
    "I-PRES-01",
    "I-PRES-02",
    "I-PRES-03",
    "I-PRES-04",
    "I-PROF-01",
    "I-PROF-02",
    "I-PROF-03",
    "I-PROF-04",
    "I-PROF-05",
    "I-PROF-06",
    "I-PROF-07",
    "I-PTC-01",
    "I-PTC-02",
    "I-PTC-03",
    "I-PTC-04",
    "I-PTC-05",
    "I-PWS-01",
    "I-PWS-02",
    "I-PWS-03",
    "I-PWS-04",
    "I-PWS-05",
    "I-PWS-06",
    "I-PWS-07",
    "I-PWS-08",
    "I-PWS-09",
    "I-PWS-10",
    "I-RT-08",
    "I-TOCE-01",
    "I-TOCE-02",
    "I-TOCE-03",
    "I-TOCE-04",
    "I-TOCE-05",
    "I-TRJ-01",
    "I-TRJ-02",
    "I-TRJ-03",
    "I-TRJ-04",
    "I-TRJ-08",
    "I-TRJ-09",
})

EXPECTED_STRUCTURAL_IDS: frozenset[str] = frozenset({
    "I-CAT-01",
    "I-ISO-01",
    "I-ISO-02",
    "I-ISO-03",
    "I-LLM-04",
    "I-PCE-05",
    "I-PMAP-01",
    "I-PMAP-03",
    "I-PRES-05",
    "I-RT-09",
    "I-RT-10",
    "I-RT-11",
    "I-RT-12",
    "I-TRACE-01",
    "I-TRACE-02",
    "I-TRACE-03",
})
