/-
TLICA.TemporalTrajectory — Deterministic profile trajectories.

This module adds the first temporal layer over the verified agency/free-will
apparatus. A trajectory is supplied as indexed profile data; `generatedBy`
records when that data follows the deterministic action-indexed projection.
The module does not assert global trajectory existence, stochastic dynamics, or
phenomenological experience of divergence.
-/

import TLICA.FreeWill
import TLICA.ProfileComparison.Pointwise

namespace TLICA.TemporalTrajectory

open TLICA.Profile
open TLICA.ProfileComparison.Pointwise
open TLICA.Agency
open TLICA.FreeWill
open TLICA.ActionProjection
open scoped ENNReal

variable {α Act : Type*}

/-- A natural-time indexed sequence of scalar profiles. -/
structure ProfileTrajectory (α : Type*) where
  /-- Profile observed or represented at natural time `n`. -/
  profileAt : ℕ → ScalarProfile α

/-- A natural-time indexed action schedule. -/
structure ActionSchedule (Act : Type*) where
  /-- Action assigned at natural time `n`. -/
  actionAt : ℕ → Act

/-- One-step branch profile from an initial profile and an action. -/
def oneStepBranch (ctx : AgencyContext α Act) (P : ScalarProfile α) (a : Act) :
    ScalarProfile α :=
  branchProfile ctx P a

/-- A supplied trajectory is generated by a supplied schedule when each
    successor profile is the deterministic projection of the previous profile
    under the scheduled action. -/
def generatedBy (ctx : AgencyContext α Act)
    (traj : ProfileTrajectory α) (sched : ActionSchedule Act) : Prop :=
  ∀ n, traj.profileAt (n + 1) =
    projectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n)

/-- Named one-step equation for a generated trajectory. -/
theorem generatedBy_step
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    traj.profileAt (n + 1) =
      projectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n) :=
  h n

/-- Direct projected-profile spelling of the generated one-step equation. -/
theorem generatedBy_step_projectedProfile
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    traj.profileAt (n + 1) =
      projectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n) :=
  generatedBy_step h n

/-- Branch-profile spelling of the generated one-step equation. -/
theorem generatedBy_step_branchProfile
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    traj.profileAt (n + 1) =
      branchProfile ctx (traj.profileAt n) (sched.actionAt n) := by
  rw [generatedBy_step h n]
  rfl

/-- One-step-branch spelling of the generated one-step equation. -/
theorem generatedBy_step_oneStepBranch
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    traj.profileAt (n + 1) =
      oneStepBranch ctx (traj.profileAt n) (sched.actionAt n) := by
  rw [generatedBy_step h n]
  rfl

/-- Future MSI contents of the scheduled branch at a time along a trajectory. -/
def trajectoryFutureContents (ctx : AgencyContext α Act)
    (traj : ProfileTrajectory α) (sched : ActionSchedule Act) (n : ℕ) :
    Set α :=
  branchFutureContents ctx (traj.profileAt n) (sched.actionAt n)

/-- `trajectoryFutureContents` unfolds to the branch-future contents at the
    scheduled action. -/
theorem trajectoryFutureContents_eq_branchFutureContents
    (ctx : AgencyContext α Act)
    (traj : ProfileTrajectory α) (sched : ActionSchedule Act) (n : ℕ) :
    trajectoryFutureContents ctx traj sched n =
      branchFutureContents ctx (traj.profileAt n) (sched.actionAt n) :=
  rfl

/-- Scheduled trajectory future contents are definitionally direct future-MSI
    contents for the scheduled projected branch. -/
theorem trajectoryFutureContents_eq_futureMSIContents
    (ctx : AgencyContext α Act)
    (traj : ProfileTrajectory α) (sched : ActionSchedule Act) (n : ℕ) :
    trajectoryFutureContents ctx traj sched n =
      futureMSIContents ctx.fam ctx.proj (traj.profileAt n) (sched.actionAt n) := by
  rw [trajectoryFutureContents_eq_branchFutureContents,
    branchFutureContents_eq_futureMSIContents]

/-- Union-domain profile distance between adjacent times. -/
noncomputable def stepUnionDistance (traj : ProfileTrajectory α) (n : ℕ) :
    ℝ≥0∞ :=
  dInfUnion (traj.profileAt n) (traj.profileAt (n + 1))

/-- Adjacent union-domain distance is nonnegative by codomain. -/
theorem stepUnionDistance_nonneg (traj : ProfileTrajectory α) (n : ℕ) :
    0 ≤ stepUnionDistance traj n :=
  bot_le

/-- Adjacent union-domain distance is bounded by the profile-comparison bound. -/
theorem stepUnionDistance_le_one (traj : ProfileTrajectory α) (n : ℕ) :
    stepUnionDistance traj n ≤ 1 := by
  unfold stepUnionDistance
  exact dInfUnion_le_one _ _

/-- For a generated trajectory, adjacent union distance unfolds to the direct
    projected successor profile. -/
theorem generatedBy_stepUnionDistance_eq_projectedProfile
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    stepUnionDistance traj n =
      dInfUnion (traj.profileAt n)
        (projectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n)) := by
  unfold stepUnionDistance
  rw [generatedBy_step h n]

/-- For a generated trajectory, adjacent union distance unfolds to the
    scheduled one-step branch. -/
theorem generatedBy_stepUnionDistance_eq_oneStepBranch
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    stepUnionDistance traj n =
      dInfUnion (traj.profileAt n)
        (oneStepBranch ctx (traj.profileAt n) (sched.actionAt n)) := by
  rw [generatedBy_stepUnionDistance_eq_projectedProfile h n]
  rfl

/-- Shared-domain profile distance between adjacent times. -/
noncomputable def stepSharedDistance (traj : ProfileTrajectory α) (n : ℕ) :
    ℝ≥0∞ :=
  dInfShared (traj.profileAt n) (traj.profileAt (n + 1))

/-- Adjacent shared-domain distance is nonnegative by codomain. -/
theorem stepSharedDistance_nonneg (traj : ProfileTrajectory α) (n : ℕ) :
    0 ≤ stepSharedDistance traj n :=
  bot_le

/-- Adjacent shared-domain distance is bounded by one when the adjacent
    profiles have nonempty shared domain. -/
theorem stepSharedDistance_le_one_of_nonempty
    (traj : ProfileTrajectory α) (n : ℕ)
    (h : ((traj.profileAt n).domain ∩
      (traj.profileAt (n + 1)).domain).Nonempty) :
    stepSharedDistance traj n ≤ 1 := by
  unfold stepSharedDistance
  exact dInfShared_le_one_of_nonempty _ _ h

/-- Adjacent shared-domain distance is infinite exactly when the adjacent
    profiles have no shared domain. -/
theorem stepSharedDistance_top_iff
    (traj : ProfileTrajectory α) (n : ℕ) :
    stepSharedDistance traj n = ⊤ ↔
      ¬ ((traj.profileAt n).domain ∩
        (traj.profileAt (n + 1)).domain).Nonempty := by
  unfold stepSharedDistance
  exact dInfShared_top_iff _ _

/-- For a generated trajectory, adjacent shared distance unfolds to the direct
    projected successor profile. -/
theorem generatedBy_stepSharedDistance_eq_projectedProfile
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    stepSharedDistance traj n =
      dInfShared (traj.profileAt n)
        (projectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n)) := by
  unfold stepSharedDistance
  rw [generatedBy_step h n]

/-- For a generated trajectory, adjacent shared distance unfolds to the
    scheduled one-step branch. -/
theorem generatedBy_stepSharedDistance_eq_oneStepBranch
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    stepSharedDistance traj n =
      dInfShared (traj.profileAt n)
        (oneStepBranch ctx (traj.profileAt n) (sched.actionAt n)) := by
  rw [generatedBy_stepSharedDistance_eq_projectedProfile h n]
  rfl

/-- Uniform stepwise temporal stability measured by union-domain distance. -/
def unionStepStable (traj : ProfileTrajectory α) (ε : ℝ≥0∞) : Prop :=
  ∀ n, stepUnionDistance traj n ≤ ε

/-- Uniform step stability gives the stated bound at each step. -/
theorem unionStepStable_step_le
    {traj : ProfileTrajectory α} {ε : ℝ≥0∞}
    (h : unionStepStable traj ε) (n : ℕ) :
    stepUnionDistance traj n ≤ ε :=
  h n

/-- Eventual stepwise temporal stability measured by union-domain distance. -/
def eventuallyUnionStepStable
    (traj : ProfileTrajectory α) (ε : ℝ≥0∞) (N : ℕ) : Prop :=
  ∀ n, N ≤ n → stepUnionDistance traj n ≤ ε

/-- Eventual step stability persists if the start index is moved later. -/
theorem eventuallyUnionStepStable_of_le_start
    {traj : ProfileTrajectory α} {ε : ℝ≥0∞} {N M : ℕ}
    (h : eventuallyUnionStepStable traj ε N)
    (hN : N ≤ M) :
    eventuallyUnionStepStable traj ε M := by
  intro n hn
  exact h n (Nat.le_trans hN hn)

/-- Uniform step stability implies eventual step stability from any start. -/
theorem eventuallyUnionStepStable_of_unionStepStable
    {traj : ProfileTrajectory α} {ε : ℝ≥0∞} (N : ℕ)
    (h : unionStepStable traj ε) :
    eventuallyUnionStepStable traj ε N := by
  intro n _hn
  exact h n

/-- Temporal divergence between two supplied trajectories, witnessed by a time
    at which their profile states are not equal. -/
structure DivergentTrajectories
    (ctx : AgencyContext α Act) (traj₁ traj₂ : ProfileTrajectory α) where
  /-- Time at which the trajectories differ. -/
  divergenceTime : ℕ
  /-- Profile states differ at the divergence time. -/
  branch_diff :
    traj₁.profileAt divergenceTime ≠ traj₂.profileAt divergenceTime

/-- One-step branches are the branch-profile API spelling. -/
theorem oneStepBranch_eq_branchProfile
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a : Act) :
    oneStepBranch ctx P a = branchProfile ctx P a :=
  rfl

/-- One-step branches are direct projected profiles. -/
theorem oneStepBranch_eq_projectedProfile
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a : Act) :
    oneStepBranch ctx P a = projectedProfile ctx.proj P a :=
  rfl

/-- Union-domain distance between two one-step deterministic branches. -/
noncomputable def oneStepBranchUnionDistance
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a b : Act) : ℝ≥0∞ :=
  dInfUnion (oneStepBranch ctx P a) (oneStepBranch ctx P b)

/-- The one-step branch union distance unfolds to the union distance between
    the corresponding branch profiles. -/
theorem oneStepBranchUnionDistance_eq_dInfUnion
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a b : Act) :
    oneStepBranchUnionDistance ctx P a b =
      dInfUnion (branchProfile ctx P a) (branchProfile ctx P b) :=
  rfl

/-- Direct projected-profile spelling of the one-step branch union distance. -/
theorem oneStepBranchUnionDistance_eq_projectedProfile
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a b : Act) :
    oneStepBranchUnionDistance ctx P a b =
      dInfUnion (projectedProfile ctx.proj P a)
        (projectedProfile ctx.proj P b) :=
  rfl

/-- One-step branch union distance is nonnegative by codomain. -/
theorem oneStepBranchUnionDistance_nonneg
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a b : Act) :
    0 ≤ oneStepBranchUnionDistance ctx P a b :=
  bot_le

/-- One-step branch union distance is bounded by the union-distance profile
    bound. -/
theorem oneStepBranchUnionDistance_le_one
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a b : Act) :
    oneStepBranchUnionDistance ctx P a b ≤ 1 := by
  unfold oneStepBranchUnionDistance
  exact dInfUnion_le_one _ _

/-- One-step branch union distance is reflexive. -/
theorem oneStepBranchUnionDistance_self
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a : Act) :
    oneStepBranchUnionDistance ctx P a a = 0 := by
  unfold oneStepBranchUnionDistance
  exact dInfUnion_self _

/-- One-step branch union distance is symmetric. -/
theorem oneStepBranchUnionDistance_symm
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a b : Act) :
    oneStepBranchUnionDistance ctx P a b =
      oneStepBranchUnionDistance ctx P b a := by
  unfold oneStepBranchUnionDistance
  exact dInfUnion_symm _ _

/-- One-step branch union distance satisfies the triangle inequality. -/
theorem oneStepBranchUnionDistance_triangle
    (ctx : AgencyContext α Act) (P : ScalarProfile α) (a b c : Act) :
    oneStepBranchUnionDistance ctx P a c ≤
      oneStepBranchUnionDistance ctx P a b +
        oneStepBranchUnionDistance ctx P b c := by
  unfold oneStepBranchUnionDistance
  exact dInfUnion_triangle _ _ _

/-- A free-will witness supplies live feasible actions whose future contents
    differ. This is the temporal-trajectory naming bridge for the existing
    branch-sensitive witness data. -/
theorem freeWillWitness_live_branch_contents_distinct
    {ctx : AgencyContext α Act} {P : ScalarProfile α}
    (w : FreeWillWitness ctx P) :
    ∃ selected alternative,
      liveAlternative ctx P selected alternative ∧
        branchFutureContents ctx P selected ≠
          branchFutureContents ctx P alternative :=
  ⟨w.selected, w.alternative, w.alternative_live, w.branch_distinct⟩

/-- One-step branch futures from the selected and alternative actions of a
    free-will witness are distinct. -/
theorem freeWillWitness_oneStep_branch_contents_distinct
    {ctx : AgencyContext α Act} {P : ScalarProfile α}
    (w : FreeWillWitness ctx P) :
    branchFutureContents ctx P w.selected ≠
      branchFutureContents ctx P w.alternative :=
  w.branch_distinct

/-- A PCE-differentiated free-will witness gives the same one-step
    branch-future distinction through its induced `FreeWillWitness`. -/
theorem pceFreeWillWitness_oneStep_branch_contents_distinct
    {ctx : AgencyContext α Act} {P : ScalarProfile α}
    (w : PCEFreeWillWitness ctx P) :
    branchFutureContents ctx P w.selected ≠
      branchFutureContents ctx P w.alternative :=
  (w.toFreeWillWitness).branch_distinct

/-- Deferred marker: stochastic trajectory models are not formalized in this
    deterministic trajectory layer. This is not a theorem claim. -/
def stochasticTrajectory_deferred : Prop := True

/-- Deferred marker: phenomenological duration is not formalized in this
    deterministic trajectory layer. This is not a theorem claim. -/
def phenomenologicalDuration_deferred : Prop := True

/-- Deferred marker: a richer temporal-continuity metric remains future work.
    This is not a theorem claim. -/
def temporalContinuityMetric_deferred : Prop := True

end TLICA.TemporalTrajectory
